--- 
- 
  become: true
  hosts: worker1
  tasks: 
    - 
      name: "Installing httpd"
      yum: 
        name: httpd
        state: latest
    - 
      name: "ensure apache is running"
      service: 
        name: httpd
        state: started
